
export const JWT_PUBLIC_KEY = process.env.JWT_PUBLIC_KEY || `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtVPKE1WipARmLgW8XPr7
wfpUttNRkuPeD4rXKx4yTYYAJLsMEsmptUmMz5wxqx1jylCKd0hI/IjZbYcrXAKZ
PMShe8eBbKX2ExI7gF+vN6z/ptd4muMvSeV0kIhqvoK2lHZe5lKwiS5UBP6+txY8
yzdLNXX26vU3zVJdjHF4AxjUyFe4sa1jLmvr2YsrloHNep326Eb8jTTDHideBfaU
tLhLubwrECMsOhbsxdt6Cg393f8h04VthWFU5XiYOAeUnYB4fATfzEkwiCz+fMQf
juu0T/UYdukiNWJ3j6AcRvdFppWiSNZtMDN3oEXKHAoQJgcymt5qYdANGrWa14iE
wQIDAQAB
-----END PUBLIC KEY-----
`;